# Generated by Django 5.1.1 on 2024-10-06 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_genres_alter_book_options_alter_book_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='books.genres'),
            preserve_default=False,
        ),
    ]
