# Generated by Django 5.1.1 on 2024-10-31 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_comment_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
    ]
