# Generated by Django 5.1.1 on 2024-10-09 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_slug'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='book',
            managers=[
            ],
        ),
    ]
