# Generated by Django 5.1.1 on 2024-10-11 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_remove_book_genre_book_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='genre',
            new_name='genres',
        ),
    ]
