# Generated by Django 5.1.1 on 2024-10-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_rename_genre_book_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='book_images/%Y/%m/%d', verbose_name='Book Image'),
        ),
    ]
