# Generated by Django 5.1.1 on 2024-10-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='book_images/%Y/%m/%d/', verbose_name='Book Image'),
        ),
    ]
