# Generated by Django 5.1.1 on 2024-10-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='genres', to='books.genres'),
        ),
    ]
