# Generated by Django 5.1.1 on 2024-10-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_alter_book_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='is_published',
            field=models.BooleanField(choices=[(1, 'Published (available for all to view)'), (0, 'Not published (available only you)')], default=1),
        ),
    ]
